name: ICare
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  flutter_bloc: ^0.21.0
  json_serializable: ^3.2.3
  url_launcher: ^5.2.0
  cached_network_image: ^2.0.0-rc
  flutter_stetho: ^0.5.0
  # File Downloading, Timeout etc.
  dio: ^3.0.3
  #List filter click
  filter_list: ^0.0.1
  #Date picker theme
  flutter_rounded_date_picker: 1.0.0
  #Signin option and data
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^0.13.4+2
  http: ^0.12.0+4
  percent_indicator: ^2.1.1
  #double back to close app
  double_back_to_close_app: ^1.2.0
  #pedometer to counter steps
  pedometer: ^1.0.0
  decimal: ^0.3.5
  #incaditors animated
  flutter_spinkit: ^4.1.2
  loading_overlay: ^0.2.1
  shimmer: ^1.1.1
  frefresh: ^1.1.0
  #stop watch timer
  stop_watch_timer:
  #heart rate
  charts_flutter: ^0.9.0
  wakelock: ^0.1.4+1
  camera:
    git:
      url: https://github.com/Renesanse/plugins.git
      path: packages/camera
      ref: flash_light
  material_design_icons_flutter: 4.0.5245
  #refresh
  pull_to_refresh: ^1.5.8
  #laucher icons
  flutter_launcher_icons: ^0.7.5
  #spin box
  flutter_spinbox: ^0.2.0
  #facebook login
  flutter_facebook_login: ^1.1.1
  #splash screen
  splashscreen:
  #audio player
  #assets_audio_player: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Tools to write binaries that run builders.
  build_runner: ^1.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fitness_app/icon_demo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fitness_app/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
